POST http://localhost:3001/pushes
content-type: application/json

{
    "user_id": 30460,
    "sport_id": 1,
    "event_id": 10058
}

###
GET http://localhost:3000/pushes

# 1477937

# [
#   {
#     "_id": "63e4cb9b6638ea2964ea0432",
#     "user_id": 30460,
#     "sport_id": 1,
#     "event_id": 1730432,
#     "incidents": 6,
#     "__v": 0
#   }

#   {
#     "_id": "63e4cb9b6638ea2964ea0432",
#     "user_id": 1400,
#     "sport_id": 1,
#     "event_id": 1730432,
#     "incidents": 6,
#     "__v": 0
#   }

#     {
#     "_id": "63e4cb9b6638ea2964ea0432",
#     "user_id": 1400,
#     "sport_id": 1,
#     "event_id": 8888,
#     "incidents": 6,
#     "__v": 0
#   }
# ]